# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sample Cocktails App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Sample Cocktails App

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SwiftyJSON'

end
